language: objective-c
osx_image: xcode10.1
xcode_project: AGImagesDownloader.xcodeproj
xcode_scheme: AGImagesDownloaderTests
branches:
  only:
  - master
script:
  xcodebuild -project AGImagesDownloader.xcodeproj -scheme AGImagesDownloaderTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
